version: '3.7'

services:
    redmine:
      image: redmine:4.0.5
      ports:
        - 30002:3000
      environment:
        REDMINE_DB_MYSQL: db
        REDMINE_DB_PASSWORD: password
      depends_on:
        - db
      restart: always
      volumes:
        - ./plantuml_macro:/usr/src/redmine/plugins/plantuml_macro
    db:
      image: mariadb:10.0
      environment:
        MYSQL_DATABASE: redmine
        MYSQL_ROOT_PASSWORD: password
      restart: always
      volumes:
        - ./mysql_conf.d:/etc/mysql/conf.d/
        - ./mysql_data:/var/lib/mysql
        - ./my.cnf:/etc/mysql/conf.d/my.cnf
      command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci

    plantuml-server:
      image: plantuml/plantuml-server
      restart: always
      ports:
        - "13080:8080"
