version: '3.7'

services:
    redmine:
      image: redmine:4.0.5
      ports:
        - 30001:3000
      environment:
        REDMINE_DB_MYSQL: db
        REDMINE_DB_PASSWORD: password
      depends_on:
        - db
      restart: always
    db:
      image: mariadb:10.0
      environment:
        MYSQL_DATABASE: redmine
        MYSQL_ROOT_PASSWORD: password
      restart: always
      volumes:
        - ./mysql_conf.d:/etc/mysql/conf.d/
        - ./mysql_data:/var/lib/mysql
